name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # app-level deps
  http: ^1.6.0
  http_certificate_pinning: ^3.0.1
  provider: ^6.1.5+1
  dartz: ^0.10.1
  equatable: ^2.0.7
  google_fonts: ^6.3.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^9.1.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5

  # feature/core packages
  ditonton_core:
    path: packages/ditonton_core
  ditonton_movies:
    path: packages/ditonton_movies
  ditonton_tv:
    path: packages/ditonton_tv

dev_dependencies:
  mockito: ^5.6.1
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.2+1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/certificates/
