name: ditonton_core
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  http_certificate_pinning: ^3.0.1
  sqflite: ^2.4.2
  google_fonts: ^6.3.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.4.0

flutter:
  uses-material-design: false
