name: ditonton_movies
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dartz: ^0.10.1
  http: ^1.2.0
  equatable: ^2.0.5
  flutter_rating_bar: ^4.0.1
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  shared_preferences: ^2.2.3
  ditonton_core:
    path: ../ditonton_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  bloc_test: ^10.0.0

flutter:
  uses-material-design: false
